### ISSUE TITLE
Top 3 users not correct

### ISSUE THREAD

**Issue by enviousdigital** [andrewlimaza/when-last-login#31]
Hi Andrew

Hate to tell you this, but it is still not performing correctly. The data did change when I installed it, but now after running the site with it for a few days - it is showing top users that aren't. I have three of four users who have logged in many times, but it is showing users who have only logged in once as the top three...

Is there any information I can share with you to help resolve?

Clare

**Comment by andrewlimaza** [comment]
Thanks for the feedback Clare, I will be working through this over the next couple of days and it should be released in the near future.

Would you mind sharing a bit more specs about your hosting environment?

* WordPress version
* Is it a Multisite.
* PHP Version
