### ISSUE TITLE
Undefined Index Error.

### ISSUE THREAD

**Issue by andrewlimaza** [andrewlimaza/when-last-login#33]
Notice
: Undefined index: show_all_login_records in
/var/www/oliceo-www/wp-content/plugins/when-last-login/when-last-login.php
on line
257

https://wordpress.org/support/topic/undefined-index-134/

**Comment by csunday-gpwa-com** [comment]
Is there a resolution to this issue?  My whole site is down.

**Comment by andrewlimaza** [comment]
Hi @csunday-gpwa-com 

This warning should not bring down your whole site.

Please can you work through this guide and let me know what errors you get?

https://yoohooplugins.com/debugging-in-wordpress/

**Comment by csunday-gpwa-com** [comment]
I found the problem, a caching plugin had cached an error page and we had to manually clear the cache and disable the plugin.

Cheri Sunday
Director of Information Technology
602-200-6930
csunday@gpwa.com<mailto:csunday@gpwa.com>
