### ISSUE TITLE
Make `wll_records` CPT optional

### ISSUE THREAD

**Issue by lkraav** [andrewlimaza/when-last-login#9]
Multiple reasons given here https://wordpress.org/support/topic/last-logins-as-posts-create-problems/

Simple solution is to have a constant based conditional check around the `init` action and logging routine.

**Comment by andrewlimaza** [comment]
Creating a filter for this. Just my preference :) - release coming soon!

**Comment by andrewlimaza** [comment]
Feel free to test version 0.6 - you may use the filter `when_last_login_show_records_table` (accepts boolean value. default is true).

Releasing this tomorrow after further testing.
